# Generated by Django 5.0.7 on 2024-10-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('departure', models.DateTimeField(default='2024-10-11 11:19', verbose_name='Departure')),
                ('price', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Price, Rub')),
                ('description', models.TextField(verbose_name='Description')),
                ('availability', models.BooleanField(default=True, verbose_name='Availability')),
                ('places', models.PositiveSmallIntegerField(default=36, verbose_name='Places left')),
            ],
            options={
                'verbose_name': 'Leg',
                'verbose_name_plural': 'Legs',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('slug', models.SlugField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('slug', models.SlugField(max_length=255)),
            ],
        ),
    ]
