# Generated by Django 5.0.7 on 2024-10-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_alter_news_options_leg_photo_news_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leg',
            name='availability',
        ),
        migrations.AlterField(
            model_name='leg',
            name='departure',
            field=models.DateTimeField(default='2024-10-12 12:00', verbose_name='Departure'),
        ),
    ]
