# Generated by Django 5.0.7 on 2024-12-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_category_options_alter_leg_departure_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='leg',
            options={'verbose_name': 'Поход', 'verbose_name_plural': 'Походы'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.RemoveField(
            model_name='leg',
            name='places',
        ),
        migrations.AddField(
            model_name='leg',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='leg',
            name='departure',
            field=models.DateTimeField(default='2024-12-17 15:24', verbose_name='Departure'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
