# Generated by Django 5.0.7 on 2024-12-21 12:51

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_news_category_alter_leg_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leg',
            name='departure',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 21, 12, 51, 8, 478165), verbose_name='Departure'),
        ),
        migrations.AlterField(
            model_name='leg',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
